### ISSUE TITLE
Importing Issue

### ISSUE THREAD

**Issue by the-leonat** [mklauber/pygame-hex-grid#1]
Installed the Module normally and i'm now not able to import the module correctly

5:  from hexmap import Map, Grid, MapUnit
     ...
20: self.map = Map(40, 30)

will lead to:

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from hexmap import Map, Grid, MapUnit
ImportError: cannot import name Map

If i try to import the modules over the python command line i will get the same error.
The funny thing is that just importing the main module by "> import hexmap" works fine.

**Comment by mklauber** [comment]
The issue has to do with the layout of code in this repository.  The actual map classes are located in the `hexmap.map` module.  Therefore, you should be able to do `from hexmap.map import Map, Grid, GridUnit`.  However, be aware that this project has been dormant for two years now, so while I will welcome pull requests, I do not plan to do active development.
